# http://php.net/supported-versions.php

language: php
os: linux
dist: xenial

jobs:
  include:

    # EOL
    - php: 5.6
    - php: 7.0

    # Current
    - php: 7.3
    - php: 7.4

  fast_finish: false

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script:
  php vendor/bin/phpunit

notifications:
  email:
    - devops@uploadcare.com
